### ISSUE TITLE
consider updating FAQ to indicate on which system to check for problems

### ISSUE THREAD

**Issue by pdp2shirts** [f5devcentral/F5-Automation-Sandbox#6]
in the section below:
Problem: Provioner fails - SSH connectivity

Provisioner fails at task [Wait for all nodes to have SSH reachability]

Solution

Make sure there is a private key of the form <<workshop_name>>-private.pem in folder f5_provisioner/provisioner/<<workshop_name>>/

it is not made clear that this command should be run from the your docker host not from one of the AWS VMs.

in section:

Problem:unable to locate credentials¶

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: NoCredentialsError: Unable to locate credentials
fatal: [localhost]: FAILED! => {"attempts": 1, "changed": false, "msg": "Failed to describe VPCs: Unable to locate credentials"}
Copy to clipboard
Solution

Set your Access Key ID and Secret Access Key under ~/.aws/credentials

[root@centos ~]# cat ~/.aws/credentials
[default]
aws_access_key_id = ABCDEFGHIJKLMNOP
aws_secret_access_key = ABCDEFGHIJKLMNOP/ABCDEFGHIJKLMNOP

There is no indication on which host these commands ought to be run.

**Comment by VDI-Tech-Guy** [comment]
fixed
