### ISSUE TITLE
consider updating ansible_use_cases_and_labs.rst 

### ISSUE THREAD

**Issue by pdp2shirts** [f5devcentral/F5-Automation-Sandbox#7]
While there is a link to the Ansible use cases clouddocs page, it is unclear that following that link is the NEXT step. the next step shows you how to teardown the lab. This might be a bit confusing. A possible method to make this more clear would be to put a note on the tear down lab.rst page that indicates one should follow this step only if they are not wanting to implement any of the use cases,  or only after they have completed running through the use cases. 
The "Next" button at the bottom of the page beckons one to click on it, but it may not be the next logical step.

**Comment by VDI-Tech-Guy** [comment]
repaired
