### ISSUE TITLE
fix instructions on F5-Automation-Sandbox/docs/teardown.rst

### ISSUE THREAD

**Issue by pdp2shirts** [f5devcentral/F5-Automation-Sandbox#8]
the instructions suggest running 
```
cd f5_provisioner/provisioner
ansible-playbook teardown_lab.yml -e @f5_vars.yml
```
 from the Ansible_server_provisioner, but I believe the earlier instructions have you build a docker container, and then issue a docker run command with the AWS keys like below

```
docker run \
-e AWS_ACCESS_KEY_ID=ABCDEFGHIJKLMNOP \
-e AWS_SECRET_ACCESS_KEY=ABCDEFGHIJKLMNOP/ABCDEFGHIJKLMNOP \
-v $(pwd)/../provisioner:/ansible/playbooks \
f5_sandbox_provisioner provision_lab.yml -e @f5_vars.yml
```

but the instructions on the teardown.rst page point to a directory `cd f5_provisioner/provisioner` that are part of the docker container, not one of the Ansible hosts. 

I think that the instructions for tearing down ought to be 

```
cd f5_provisioner/provisioner
docker run \
-e AWS_ACCESS_KEY_ID=ABCDEFGHIJKLMNOP \
-e AWS_SECRET_ACCESS_KEY=ABCDEFGHIJKLMNOP/ABCDEFGHIJKLMNOP \
-v $(pwd)/../provisioner:/ansible/playbooks \
 f5_sandbox_provisioner teardown_lab.yml -e @f5_vars.yml
```

**Comment by VDI-Tech-Guy** [comment]
repaired
